### ISSUE TITLE
How to pass file descriptors between processes with it ?

### ISSUE THREAD

**Issue by Christina2333** [mitsuhiko/tokio-unix-ipc#12]
I tried to send the file descriptor using `Bootstrapper.send()` method but it doesn't work. `Bootstrapper.send()` method seems to transmit the file descriptor as an ordinary integer, without conversion by the operating system kernel. Similar to the functionality of this crate: https://github.com/polachok/passfd.

There is another question I wonder: 
Why is the `Bootstrapper#sender` wrapped in `RefCell` instead of `Arc`, so that `Bootstrapper` cannot be used in asynchronous traits.

Looking forward to your reply!

**Comment by mitsuhiko** [comment]
The `send` method uses serialization. If you wrap the fd / object that converts into an fd in [`HandleRef`](https://docs.rs/tokio-unix-ipc/latest/tokio_unix_ipc/serde/struct.HandleRef.html) or [`Handle`](https://docs.rs/tokio-unix-ipc/latest/tokio_unix_ipc/serde/struct.Handle.html) you can pass it conveniently this way.

With regards to the bootstapper sender I am not sure right now what the usecase is and what stands against implementing it. In general a `RefCell` is not replaceable with an `Arc`, a `Mutex` might be but comes at an increased cost. If the bootsrapper is an issue, please open a separate issue for it.
