### ISSUE TITLE
support for `SO_PEERCRED`

### ISSUE THREAD

**Issue by cgwalters** [mitsuhiko/tokio-unix-ipc#4]
In one project I'm using `SO_PEERCRED`: https://github.com/coreos/bootupd/blob/main/src/ipc.rs - looking at using this crate instead.  What do you think about exposing that via an API?

The usual pattern here is to pass credentials on the first message.  In the above code I represented this as a state machine encoded via structs; e.g. perhaps we'd add `RawAuthenticatingSender` and `RawUnauthenticatedReceiver`, where e.g.

```
impl RawUnauthenticatedReceiver {
   pub async fn recv(self) -> Result<(RawReceiver, Credentials, Vec<u8>, Option<Vec<RawFd>>)>
```

Note this consumes the unauthenticated type and returns credentials.  Would need to debate exposing e.g. https://docs.rs/nix/latest/nix/sys/socket/struct.UnixCredentials.html or (probably better for semver) a new struct here.

Alternatively we could add `recv_with_creds()` and `send_with_creds()` to the raw types.

**Comment by mitsuhiko** [comment]
Good question. While I think the `RawUnauthenticatedReceiver` is interesting I wonder if it's not in practice too impractical to have to swap the type after the first message. I'm slightly favoring the `recv_with_creds` option. This would also translate better through the serde version if needed.
